name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Run lint
      run: |
        pip3 install -U poetry==1.8.2
        poetry install -n
        poetry run black --check .
        poetry run isort --check .
